name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest #this is github's ubuntu machine

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
      #the uses: actions/checkout@v2 step is used to check out the code from your repository, 
      #which makes the repository's contents available to the runner(github's ubuntu machine) for the duration of the workflow run.
      #This allows you to work with files and scripts that are part of your repository in your workflow.

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: | #this will run on github's ubuntu machine
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts 
        ssh -t -i keyfile ubuntu@ec2-16-171-175-49.eu-north-1.compute.amazonaws.com "sudo bash ~/deploy.sh"

